### ISSUE TITLE
Error on make command

### ISSUE THREAD

**Issue by mtreca** [hauleth/asyncdo.vim#3] opened 2017-12-06 17:17 UTC
Hi,

I get the following error on calling asyncdo to make a LaTeX file in Neovim:

```
Error detected while processing function <lambda>8[1]..<SNR>52_finalize:
line    3:                                                              
E40: Can't open errorfile /tmp/nvimwyvfNv/2
```

I was able to reproduce the issue using this minimal vimrc and calling `Make`:

```
set errorformat=%f:%l:\ %m,%f:%l-%\\d%\\+:\ %m
set makeprg=rubber\ -f\ -d\ -q\ -s\ --warn=misc\ '%'
call plug#begin('~/.vim/plugged')
Plug 'hauleth/asyncdo.vim'
call plug#end()
command! -bang -nargs=* Make call asyncdo#run(<bang>0, &makeprg, <f-args>)
```

Regular `make` works fine on the same file. Any idea? Thanks!

**Comment by hauleth** [comment] 2017-12-07 00:52
Do you have write access to `/tmp/nvimwyvfNv`?

**Comment by hauleth** [comment] 2017-12-07 01:51
Also does that happen when using other tools (other than `rubber` whatever this is).

**Comment by vxid** [comment] 2017-12-07 15:47
Thanks for the reply. I own the nvim directory (`drwx`).
Using `makeprg=pdflatex\ '%'` results in the same issue (regular `make` works as well).

**Comment by hauleth** [comment] 2017-12-07 15:49
@vxid I am not speaking about `nvim` directory but about `/tmp` directory and `/tmp/nvimwyvfNv`

**Comment by vxid** [comment] 2017-12-07 15:59
Yes I should have been clear that's the one I was mentioning.

**Comment by vxid** [comment] 2017-12-07 16:00
Interestingly I just read about `makeef` and `errorfile`. I tried to set it manually to `tmp/make.log` but neovim seems to override that setting (both using plain `make` and `Make`).

**Comment by hauleth** [comment] 2017-12-08 12:21
@vxid this is expected behaviour as I generate new temp filename each time you run `asyncdo#*` functions. After job is done such file is deleted. For some reason it seems that this file is deleted before it can be loaded.

What OS are you using? And with NeoVim version?

**Comment by vxid** [comment] 2017-12-08 12:36
I'm using Antergos (but basically Arch + few extra repos). I use neovim version 0.2.2-1.

**Comment by vxid** [comment] 2017-12-08 13:03
I tried it on regular Vim to be sure, same error.

**Comment by hauleth** [comment] 2017-12-08 14:15
Does `touch /tmp/nviXfFSHC/3` returns error? If not then does file exists afterwards?

**Comment by vxid** [comment] 2017-12-08 14:32
`touch` returns no errors. Moreover, if I touch `tmp/nvimxxx/i` just before try i in `make` then no error is returned but no compilations takes place (and quickfix window is empty).

**Comment by vxid** [comment] 2018-01-23 11:29
A quick update since I recently had more time to investigate it.

Setting `setlocal makeprg=rubber\ -f\ -d\ -q\ -s\ --warn=misc` and running `:Make %` or a plain regular `:make %` works as expected. I still don't get why the initial command doesn't work (appending `'%'` at the end, which regular `make` understands) but a simple workaround is to bind `:Make %<CR>`.

**Comment by vxid** [comment] 2018-01-26 11:12
Last update. Using an absolute path expansion works. I don't know if this solution is should be considered a workaround to a bug or standard behavior (feel free to close the issue if it is the latter):

```
if filereadable('Makefile')
    setlocal makeprg=make
else
    exec "setlocal makeprg=rubber\\ -f\\ -d\\ -q\\ -s\\ --warn=misc\\ " . expand("%:p")
endif
```

Thanks for the help!

**Closed as completed** 2018-09-24 13:51 UTC
Labels: bug, help wanted
